const AUTHENTICATE_ROUTE = {
  LOGIN: '@AUTHENTICATE_ROUTE/LOGIN',
  REGISTER: '@AUTHENTICATE_ROUTE/REGISTER',
};

const APP_ROUTE = {
  MAIN_TAB: '@APP_ROUTE/MAIN_TAB',
};

const HOME_ROUTE = {
  ROOT: '@HOME_ROUTE/ROOT',
  HOME_SCREEN: '@HOME_ROUTE/HOME_SCREEN',
};

const BOTTOMTAB_ROUTE = {
  ROOT : '@BOTTOMTAB_ROUTE/ROOT',
  BOTTOMTAB : '@BOTTOMTAB_ROUTE/BOTTOMTAB'
}

const TAB_NAVIGATION_ROOT = {
  HOME_ROUTE,
  AUTHENTICATE_ROUTE,
  BOTTOMTAB_ROUTE
};

export { APP_ROUTE, TAB_NAVIGATION_ROOT, AUTHENTICATE_ROUTE, HOME_ROUTE,BOTTOMTAB_ROUTE};
