const AUTHENTICATE_ROUTE = {
  LOGIN: '@AUTHENTICATE_ROUTE/LOGIN',
  REGISTER: '@AUTHENTICATE_ROUTE/REGISTER',
};

const APP_ROUTE = {
  MAIN_TAB: '@APP_ROUTE/MAIN_TAB',
};

const HOME_ROUTE = {
  ROOT: '@HOME_ROUTE/ROOT',
  HOME_SCREEN: '@HOME_ROUTE/HOME_SCREEN',
};

const BOTTOMTAB_ROUTE = {
  ROOT : '@BOTTOMTAB_ROUTE/ROOT',
  BOTTOMTAB : '@BOTTOMTAB_ROUTE/BOTTOMTAB'
}
const SETTING_ROUTE = {
  ROOT : '@SETTING_ROUTE/ROOT',
  SETTING_SCREEN: '@SETTING_ROUTE/SETTING_SCREEN'
}
const ADDNOTE_ROUTE = {
  ROOT : '@ADDNOTE_ROUTE/ROOT',
  ADDNOTE_SCREEN : '@ADDNOTE_ROUTE/ADDNOTE_SCREEN'
}

const TAB_NAVIGATION_ROOT = {
  HOME_ROUTE,
  AUTHENTICATE_ROUTE,
  BOTTOMTAB_ROUTE,
  SETTING_ROUTE,
  ADDNOTE_ROUTE
};

export { APP_ROUTE, TAB_NAVIGATION_ROOT, AUTHENTICATE_ROUTE, HOME_ROUTE,BOTTOMTAB_ROUTE,SETTING_ROUTE, ADDNOTE_ROUTE};
